name: Build Android Release

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name (optional)'
        required: false
        default: ''

env:
  JAVA_VERSION: '17'
  NODE_VERSION: '18'
  ANDROID_BUILD_TOOLS_VERSION: '35.0.0'
  ANDROID_PLATFORM_VERSION: '35'
  ANDROID_COMPILE_SDK: '35'
  ANDROID_TARGET_SDK: '35'

jobs:
  build:
    name: Build Android APK & AAB
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      # Setup Node.js
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Accept Android licenses
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      # Install Android SDK components for SDK 35
      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-${{ env.ANDROID_PLATFORM_VERSION }}"
          sdkmanager "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}"
          sdkmanager "extras;android;m2repository"
          sdkmanager "extras;google;m2repository"

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install Cordova CLI
      - name: Install Cordova CLI
        run: npm install -g cordova

      # Install project dependencies
      - name: Install npm dependencies
        run: npm ci || npm install

      # Add Android platform
      - name: Add Android platform
        run: |
          cordova platform remove android || true
          cordova platform add android@latest

      # Update config.xml for SDK 35
      - name: Update SDK version in config.xml
        run: |
          # Check if preference already exists, update or add
          if grep -q "android-targetSdkVersion" config.xml; then
            sed -i 's/android-targetSdkVersion" value="[0-9]*"/android-targetSdkVersion" value="${{ env.ANDROID_TARGET_SDK }}"/g' config.xml
          else
            sed -i '/<platform name="android">/a\        <preference name="android-targetSdkVersion" value="${{ env.ANDROID_TARGET_SDK }}" />' config.xml
          fi
          
          if grep -q "android-compileSdkVersion" config.xml; then
            sed -i 's/android-compileSdkVersion" value="[0-9]*"/android-compileSdkVersion" value="${{ env.ANDROID_COMPILE_SDK }}"/g' config.xml
          else
            sed -i '/<platform name="android">/a\        <preference name="android-compileSdkVersion" value="${{ env.ANDROID_COMPILE_SDK }}" />' config.xml
          fi

      # Update build.gradle for SDK 35
      - name: Update Gradle files for SDK 35
        run: |
          # Update project level build.gradle if exists
          if [ -f "platforms/android/build.gradle" ]; then
            sed -i "s/compileSdkVersion [0-9]*/compileSdkVersion ${{ env.ANDROID_COMPILE_SDK }}/g" platforms/android/build.gradle
            sed -i "s/targetSdkVersion [0-9]*/targetSdkVersion ${{ env.ANDROID_TARGET_SDK }}/g" platforms/android/build.gradle
          fi
          
          # Update app level build.gradle
          if [ -f "platforms/android/app/build.gradle" ]; then
            sed -i "s/compileSdkVersion [0-9]*/compileSdkVersion ${{ env.ANDROID_COMPILE_SDK }}/g" platforms/android/app/build.gradle
            sed -i "s/targetSdkVersion [0-9]*/targetSdkVersion ${{ env.ANDROID_TARGET_SDK }}/g" platforms/android/app/build.gradle
            sed -i "s/compileSdk [0-9]*/compileSdk ${{ env.ANDROID_COMPILE_SDK }}/g" platforms/android/app/build.gradle
            sed -i "s/targetSdk [0-9]*/targetSdk ${{ env.ANDROID_TARGET_SDK }}/g" platforms/android/app/build.gradle
          fi
          
          # Update cdvBuildTools version
          if [ -f "platforms/android/cdvBuildTools/build.gradle" ]; then
            sed -i "s/compileSdkVersion [0-9]*/compileSdkVersion ${{ env.ANDROID_COMPILE_SDK }}/g" platforms/android/cdvBuildTools/build.gradle
          fi

      # Update gradle.properties for SDK 35 compatibility
      - name: Update gradle.properties
        run: |
          GRADLE_PROPS="platforms/android/gradle.properties"
          if [ -f "$GRADLE_PROPS" ]; then
            # Add or update properties for SDK 35
            echo "" >> $GRADLE_PROPS
            echo "# SDK 35 compatibility" >> $GRADLE_PROPS
            echo "android.useAndroidX=true" >> $GRADLE_PROPS
            echo "android.enableJetifier=true" >> $GRADLE_PROPS
          fi

      # Decode Keystore (for signed release builds)
      - name: Decode Keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android.keystore

      # Build Release APK (Unsigned)
      - name: Build Unsigned Release APK
        if: ${{ secrets.KEYSTORE_BASE64 == '' }}
        env:
          GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false"
        run: |
          cordova build android --release -- \
            --gradleArg=-PcdvCompileSdkVersion=${{ env.ANDROID_COMPILE_SDK }} \
            --gradleArg=-PcdvTargetSdkVersion=${{ env.ANDROID_TARGET_SDK }}

      # Build Release APK (Signed)
      - name: Build Signed Release APK
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false"
        run: |
          cordova build android --release -- \
            --keystore=android.keystore \
            --storePassword="$KEYSTORE_PASSWORD" \
            --alias="$KEY_ALIAS" \
            --password="$KEY_PASSWORD" \
            --packageType=apk \
            --gradleArg=-PcdvCompileSdkVersion=${{ env.ANDROID_COMPILE_SDK }} \
            --gradleArg=-PcdvTargetSdkVersion=${{ env.ANDROID_TARGET_SDK }}

      # Build Release AAB (Unsigned)
      - name: Build Unsigned Release AAB
        if: ${{ secrets.KEYSTORE_BASE64 == '' }}
        env:
          GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false"
        run: |
          cordova build android --release -- \
            --packageType=bundle \
            --gradleArg=-PcdvCompileSdkVersion=${{ env.ANDROID_COMPILE_SDK }} \
            --gradleArg=-PcdvTargetSdkVersion=${{ env.ANDROID_TARGET_SDK }}

      # Build Release AAB (Signed)
      - name: Build Signed Release AAB
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false"
        run: |
          cordova build android --release -- \
            --keystore=android.keystore \
            --storePassword="$KEYSTORE_PASSWORD" \
            --alias="$KEY_ALIAS" \
            --password="$KEY_PASSWORD" \
            --packageType=bundle \
            --gradleArg=-PcdvCompileSdkVersion=${{ env.ANDROID_COMPILE_SDK }} \
            --gradleArg=-PcdvTargetSdkVersion=${{ env.ANDROID_TARGET_SDK }}

      # Get app version from config.xml
      - name: Get App Version
        id: version
        run: |
          VERSION=$(grep -oP 'version="\K[^"]+' config.xml | head -1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "App Version: $VERSION"

      # Find and rename build outputs
      - name: Prepare build artifacts
        run: |
          mkdir -p build-output
          
          # Find APK
          APK_PATH=$(find platforms/android -name "*.apk" -type f | grep -E "(release|Release)" | head -1)
          if [ -n "$APK_PATH" ]; then
            cp "$APK_PATH" build-output/app-release-${{ steps.version.outputs.version }}.apk
            echo "APK copied: $APK_PATH"
          fi
          
          # Find AAB
          AAB_PATH=$(find platforms/android -name "*.aab" -type f | grep -E "(release|Release)" | head -1)
          if [ -n "$AAB_PATH" ]; then
            cp "$AAB_PATH" build-output/app-release-${{ steps.version.outputs.version }}.aab
            echo "AAB copied: $AAB_PATH"
          fi
          
          ls -la build-output/

      # Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ steps.version.outputs.version }}
          path: build-output/*.apk
          retention-days: 30

      # Upload AAB artifact
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab-${{ steps.version.outputs.version }}
          path: build-output/*.aab
          retention-days: 30

      # Clean up keystore
      - name: Clean up keystore
        if: always()
        run: rm -f android.keystore

  # Create GitHub Release (only on tags)
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        id: tag_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # Download artifacts
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          pattern: release-apk-*
          path: release-assets
          merge-multiple: true

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          pattern: release-aab-*
          path: release-assets
          merge-multiple: true

      - name: List release assets
        run: ls -la release-assets/

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tag_version.outputs.version }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            release-assets/*.apk
            release-assets/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
